
mainpage:
    path:     /
    defaults: { _controller: default_controller:indexAction }

addRide:
    path:     /addRide
    defaults: { _controller: default_controller:addRideAction }

addRideStamp:
    path:     /addRideStamp
    defaults: { _controller: default_controller:addRideStampAction }

