
mainpage:
    path:     /
    defaults: { _controller: default_controller:indexAction }

addRide:
    path:     /addRide
    defaults: { _controller: default_controller:addRideAction }

addRideStamp:
    path:     /addRideStamp
    defaults: { _controller: default_controller:addRideStampAction }

authorizeStrava:
    path:     /strava/authorize
    defaults: { _controller: strava_controller:authorizeAction }

returnStrava:
    path:     /strava/return
    defaults: { _controller: strava_controller:returnAction }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"