
services:
    default_controller:
        class: AppBundle\Controller\DefaultController
        arguments: ["@drafter_service", '@templating', '@form.factory', "%strava_client_id%"]

    strava_controller:
        class: AppBundle\Controller\StravaController
        arguments: ["@strava_service", '@templating']

    strava_service:
        class: AppBundle\Service\StravaService
        arguments: ["@strava_club_repository", "@strava_ride_repository", "@strava_api_client"]

    drafter_service:
        class: AppBundle\Service\DrafterService
        arguments: ["@database_ride_repository", "@database_ride_stamp_repository", "@ride_mint", "@ruler_service", "@filter_service"]

    database_ride_repository:
        class: AppBundle\Repository\DatabaseRideRepository
        arguments: ["@doctrine.orm.default_entity_manager", "@strava_adapter"]

    strava_club_repository:
        class: AppBundle\Repository\StravaClubRepository
        arguments: ["@doctrine.orm.default_entity_manager"]

    strava_ride_repository:
        class: AppBundle\Repository\StravaRideRepository
        arguments: ["@doctrine.orm.default_entity_manager"]
    strava_api_client:
      class: AppBundle\Service\StravaApiClient
      arguments: ["%strava_client_id%", "%strava_client_secret%"]

    strava_adapter:
        class: AppBundle\Service\StravaAdapter
        arguments: ["@strava_ride_repository"]

    database_ride_stamp_repository:
        class: AppBundle\Repository\DatabaseRideStampRepository
        arguments: ["@doctrine.orm.default_entity_manager"]

    ride_mint:
        class: AppBundle\Entity\RideMint

    filter_service:
        class: AppBundle\Service\FilterService

    ruler_service:
        class: AppBundle\Service\RulerService

    app.command.mint_missing_rides_command:
        class: AppBundle\Command\MintMissingRidesCommand
        arguments: ["@drafter_service"]
        tags:
            - { name: console.command }