
services:
    default_controller:
        class: AppBundle\Controller\DefaultController
        arguments: ["@drafter_service", '@templating', '@form.factory']

    drafter_service:
        class: AppBundle\Service\DrafterService
        arguments: ["@database_ride_repository", "@database_ride_stamp_repository"]

    database_ride_repository:
        class: AppBundle\Repository\DatabaseRideRepository
        arguments: ["@doctrine.orm.default_entity_manager"]

    database_ride_stamp_repository:
        class: AppBundle\Repository\DatabaseRideStampRepository
        arguments: ["@doctrine.orm.default_entity_manager"]
