
services:
    default_controller:
        class: AppBundle\Controller\DefaultController
        arguments: ["@drafter_service", '@templating', '@form.factory']

    drafter_service:
        class: AppBundle\Service\DrafterService
        arguments: ["@database_ride_repository", "@database_ride_stamp_repository", "@ride_mint", "@ruler_service"]

    database_ride_repository:
        class: AppBundle\Repository\DatabaseRideRepository
        arguments: ["@doctrine.orm.default_entity_manager"]

    database_ride_stamp_repository:
        class: AppBundle\Repository\DatabaseRideStampRepository
        arguments: ["@doctrine.orm.default_entity_manager"]

    ride_mint:
        class: AppBundle\Entity\RideMint

    ruler_service:
        class: AppBundle\Service\RulerService

    app.command.mint_missing_rides_command:
        class: AppBundle\Command\MintMissingRidesCommand
        arguments: ["@drafter_service"]
        tags:
            - { name: console.command }