# src/AppBundle/Resources/config/doctrine/RideStamp.orm.yml
AppBundle\Entity\RideStamp:
  type: entity
  table: ridestamp
  id:
    id:
      type: integer
  fields:
    dayOfWeek:
      type: integer
    name:
      type: string
      length: 100
    locationDescription:
      type: string
      length: 100
    gpsLon:
      type: float
    gpsLat:
      type: float
    distance:
      type: integer
    gear:
      type: string
      length: 100
    rideClockHour:
      type: integer
    rideClockMinute:
      type: integer
