# src/AppBundle/Resources/config/doctrine/Ride.orm.yml
AppBundle\Entity\Ride:
  type: entity
  table: ride
  id:
    id:
      type: integer
  fields:
    name:
      type: string
      length: 100
    locationDescription:
      type: string
      length: 100
      nullable: true
    gpsLocation:
      type: gpslocation
      nullable: true
    beginning:
      type: datetime
    distance:
      type: integer
    gear:
      type: string
      length: 100

#  manyToOne:
#    owner:
#      nullable: true
#      targetEntity: AppBundle\Entity\User
#      mappedBy: ownerId
#      cascade:
#        - persist