# src/AppBundle/Resources/config/doctrine/RideStamp.orm.yml
AppBundle\Entity\RideStamp:
    type: entity
    table: ridestamp
    id:
        id:
            type: integer
    fields:
        dayOfWeek:
            type: integer
        rideName:
            type: string
            length: 100
        rideLocation:
            type: string
            length: 100
        rideClockHour:
            type: integer
        rideClockMinute:
            type: integer
