# src/AppBundle/Resources/config/doctrine/StravaRideOccurency.orm.yml
AppBundle\Entity\StravaRideOccurrency:
  type: entity
  table: stravarideoccurrency
  id:
    id:
      type: integer
  fields:
    date:
      type: datetime
